environments:
  staging:
  release:
---
helmDefaults:
  createNamespace: true
  waitForJobs: true

repositories:
 - name: istio
   url: https://istio-release.storage.googleapis.com/charts




releases:
- name: istiod
  namespace: istio-system
  chart: istio/istiod 



- name: ilb-gateway
  namespace: istio-ingress
  chart: istio/gateway 
  needs:
  - istio-system/istiod