# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: waddahahmad/ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ttt"

ui:
  uiConf: 
    REACT_APP_SERVER: ilb-gateway-staging.istio-ingress.svc.cluster.local
    REACT_APP_SERVER_ID: ilb-gateway-staging.istio-ingress.svc.cluster.local
  nginxConf: 
    nginx.conf: |
      worker_processes 4;

      events { worker_connections 1024; }

      http {
          upstream api {
            server ilb-gateway-staging.istio-ingress.svc.cluster.local;
          }

          proxy_connect_timeout 5s;
          proxy_read_timeout 60s;
          proxy_send_timeout 60s;
          proxy_http_version 1.1;

          server {
              listen 3000;
              error_log /var/log/nginx/error.log debug;
              server_name ui.ffb.svc.cluster.local;

              location / {
                  root /usr/share/nginx/html;
                  include /etc/nginx/mime.types;
                  try_files $uri $uri/ /index.html;
              }
              location /api/ {
                  proxy_pass http://api;
                  proxy_set_header Host ui.ffb.svc.cluster.local;

              }
          }
      }
      
imagePullSecrets: []


service:
  type: LoadBalancer
  port: 3000
  targetPort: 3000