# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


ui:
  network:
    name: ui-port
    containerPort: 3000
    protocol: TCP
  command: [nginx, -g, daemon off;]
  
